name: 'WissKI Grain, Yeast, and Water'
description: 'WissKI base environment with mandatory modules.'
type: 'Site'

install:
  - imce
  - inline_entity_form
  - wisski

config:
  strict: false
  import:
    imce: "*"
    inline_entity_form: "*"
    wisski: "*"
